server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\Users\tjdgm\Documents\sm-wapi-v2-5\native-file-repo
#        git:
#          uri: https://github.com/smartmeteringV2-5/native-file-repo.git
#          username: ksmartpia8530
#          password: kspia01!@#
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
